print("Hello Wrold")
print("My name is saber")
print("My major is Electrical Engineering")
print("My city is Lahijan")
print("I'm 26 years old")
print("My favorit programming languages are python and C++")
print("this line is the end of code in this project")
